[package]
name = "helium-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
slab = "0.4"
foldhash = "0.1"
itertools = "0.14"
rand = "0.9"
indoc = "1"
gcd = "2"
rayon = "1"
maplit = "1"

[dev-dependencies]

[profile.release]
lto = "thin"
debug = true
